### ISSUE TITLE
GS "Strongarm stance" 35% damage bonus is not taken into account for remote players

### ISSUE THREAD

**Issue by coavins** [coavins/mhrise-coavins-dps#46]
**Describe the bug**
Greatsword "Strongarm stance" grants a 35% bonus to damage which is not reflected in the damage charts of other players. The GS user does see the correct damage reported.

**Steps to Reproduce**
For example:
1. Use greatsword
2. Use strongarm stance
3. Attack monster with any attack (?)
4. See disparity between reported numbers on different players' charts

**Expected behavior**
Remote players should take into account other players' active bonuses to damage.

See bug and comments:
https://www.nexusmods.com/monsterhunterrise/mods/68?tab=bugs

**Comment by coavins** [comment]
I haven't been able to reproduce this yet, and I also haven't found any documentation of any 35% bonus to damage related to this skill.

**Comment by SeppNel** [comment]
It definetly gives a 35% damage bonus.
Normal TCS = 414
Strongarm TCS = 558
This is with 0 affinity and the timing done correctly in the charge.

It only tracks this bonus correctly for local players
Local:
![local](https://user-images.githubusercontent.com/35899928/178224557-fb7ba530-f0d1-4d0b-8d7d-33654e313586.png)

Network:
![network](https://user-images.githubusercontent.com/35899928/178224595-105facd1-0684-4e59-b94f-555033613a6c.png)

You can see that the network player shows the same damage as if it was a normal TCS

**Comment by coavins** [comment]
Thanks, this is very helpful.

**Comment by Daniel-Poke** [comment]
Rather than raise a new bug I just thought I'd comment in here as well since the cause may be related.

My buddies and I run Lance, Hunting Horn and Bow, and we'll often have quite different numbers after a hunt. We thought it might be a config/record inconsistency so I had them use my config JSON file. But same result.

I didn't individually test all attacks to try work what buffs/attacks cause the desync, but if we go to a training dummy and all beat the crap out of it, the total damage slowly gets less accurate over time. After hunts some of us are 10+ points less in mDPS (60 on client, 50 on remote).

**Comment by coavins** [comment]
Thanks for that information. It looks like this expansion may have introduced some kind of change to the damage calculation which results in this disparity between local and remote numbers, possibly related to personal buffs. We've always had issues with some damage not being tracked, but this idea that local vs remote is different even though both sides are capturing the attack is something we haven't seen before. There must be some new mechanism that we need to find in the engine which is responsible for this, but I don't yet have any leads nor much time to investigate.

I haven't heard anyone saying the local numbers are missing anything yet, so at least there's that.

**Comment by coavins** [comment]
I'm going to close this as a duplicate of #47 just to clean up the issue list a bit
